name: rootalli_ai_app
description: This is an assignment app from RootalliAI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  flutter_dash: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.4
  json_annotation: ^4.7.0
  percent_indicator: ^4.0.1
  intl: ^0.17.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.3.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

